### ISSUE TITLE
Purging Deleted Listener's Details

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#109]
When a listener is deleted, and when the news and magazine wallet stocks are '0' and any memory stick player has been returned so it can be unticked, then that listener's details can be purged (all records permanently removed except that the wallet number is reserved for a year incase a wallet is unexpectedly returned). The Purge button for that listener is enabled in the browse menu for deleted wallets.

**Comment by audrius-a** [comment]
Chris, as mentioned in an email, wallet stock is treated slightly differently from what is suggested above. Stock being 0 means that 3 wallets have been sent to the listener. When a wallet is returned the stock is incremented. As only 3 wallets are issued to the listener, when the stock value goes up to 3 then means all wallets have been returned. To make as you suggested I would need to change how stock is handled for deleted listeners. At the moment the "Purge" option is available when the player has been returned and stock is 3.

**Comment by achrisdale** [comment]
Hi Audrius,
it seems that doing as I asked for in #109 is going to be difficult. I'll 
ask our computer operators if they would be OK with changing our 
procedures so that we end up with a stock of '3' and '1' wallets instead 
of '0' and '0' stock for when we are ready to 'purge' a deleted listener's 
details. Presumably it will still be OK to need any memory stick player to 
have been collected. I can also copy to the Birmingham representatives.

Regards,

Chris

In message ***@***.***>

**Comment by audrius-a** [comment]
It's doable. We just need to switch around and track "wallets issued" and "wallets sent". It probably would be useful to other TN branches as they might use different amounts of wallets per listener.

**Comment by achrisdale** [comment]
It's one of the other issues for the administrator to be able to change 
the number of wallets per listener.


In message ***@***.***>

**Comment by audrius-a** [comment]
I think there is more to it than just changing that number as it would
affect all listeners, old and new. So this might be the case of shooting
two birds with a single shot.

**Comment by achrisdale** [comment]
OK. needs further thought may be. I had thought that setting the number of 
wallets per listener would just be done once when they start to use TNBase 
but of course they may want to change it later.

Chris

In message ***@***.***>

**Comment by achrisdale** [comment]
Hi Audrius,
just thinking where we are with this? You said that it's doable. Is that 
you have now thought of away that isn't too difficult, to allow deleted 
listener's wallets to be purged when we have set the stock of wallets '0'?

If this still is difficult I could ask the computer operators what they 
think about requiring the wallet stock to be '3' before purging is 
enabled. At present we have many deleted wallets numbers that can't be 
purged because the stock was set to '0'.

Regards,

Chris



In message ***@***.***>

**Comment by achrisdale** [comment]
Hi Audrius,
I'm just writing my report for the committee meeting next Monday. Can I 
check with you that Issue #109 is now doable although it isn't urgent? If 
not I'll need to have another look at the requirement. I don't want to be 
asking for something that is difficult to implement.

Chris

In message ***@***.***>

**Comment by audrius-a** [comment]
Hi Chris,

Sorry I was away the whole week and just remembered I have not replied to
you. It's not a hard thing to do to make that form appear different. But we
need to define exactly how it should work. For comparison, the user login
feature is by far more complicated.

Audrius

**Comment by achrisdale** [comment]
Hi Audrius,I'm hoping that when we can say that all available wallets for a deleted listener have been removed from stock and any memory stick player has been recovered we can then decide to purge that listener's details completely from the records except that the wallet number is reserved for a year. If a missing wallet is subsequently returned and scanned in it will just give the message "This wallet is no longer in use" and so be removed. I'm presently away for a couple of days with friends in a  hotel in Portsmouth so don't have easy access to all previous correspondence. I'll be back later on Wednesday.Hope you had a good week away.ChrisSent from my Galaxy
-------- Original message --------From: Audrius ***@***.***> Date: 05/06/2023  12:56  (GMT+00:00) To: achrisdale/TNBase ***@***.***> Cc: Chris Dale ***@***.***>, Author ***@***.***> Subject: Re: [achrisdale/TNBase] Purging Deleted Listener's Details (Issue #109) 
Hi Chris,

Sorry I was away the whole week and just remembered I have not replied to
you. It's not a hard thing to do to make that form appear different. But we
need to define exactly how it should work. For comparison, the user login
feature is by far more complicated.

Audrius

**Comment by achrisdale** [comment]
Hi Audrius,
have you had time to look at this yet? As mentioned it's not really urgent.
Just counted about 120 deleted listeners who have not been purged yet.
