### ISSUE TITLE
Query: Adding help files

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#116]
Hi Audrius, I have updated my TNBase instruction document. Can I add it so it displays when 'Help', 'View help' is selected, or do you need to add it when compiling the next release? What file format? Is rtf or pdf OK?  
I can e-mail a copy to you if you would like to check it for mistakes or anything missing.
Regards,
Chris

**Comment by audrius-a** [comment]
The best way to display help documentation in WinForms is using CHM format. It's not easy to edit directly so it's best to use software like HelpNDoc. I can show you how to work with it or I can copy your documentation into the right format and include with the next release.

**Comment by achrisdale** [comment]
OK Audrius. are WinForms and HelpNDoc free to download, or do you know if they are available on Linux? As you may know I don't use MS Windows much. If not I can e-mail the rtf doc I have been updating. Either way, it would be good to include it with the next release. Chris

**Comment by achrisdale** [comment]
OK. I can now see that WinForms seems to part of or associated with .NET7 framework, which I suppose I must have already to run TNBase. Need to have closer look. WinForms seems to be a Windows only app so I have now downloaded that onto my Windows 10 PC. Need to have a look at it when I have found WinForms, hopefully imported my RTF document and managed to save as a 'CMH' file.

**Comment by audrius-a** [comment]
WinForm is the platform that TNBase is based on. It doesn't work on Linux I'm afraid. CHM format is the standard help file format for Windows applications. As I've mentioned, I'm using HelpNDoc application to generate CHM file. This application is also Windows only and has it's own format with extension `.hnd`. For the TNBase I have HnD file stored in Docs/Help Documentation.hnd of this repository. This is the file you would need to edit. Then, using HelpNDoc generate CHM file and replace src/TNBase/Resource/TNBase.chm with it. Of course, I can help you with that.

**Comment by achrisdale** [comment]
Thanks Audrius. As mentioned in my last comment I now have WinForms on my Windows 10 PC. I need to find out how to import my .rtf. I'm not intending to type the whole document again!

**Comment by audrius-a** [comment]
This has been done as part of #118
