### ISSUE TITLE
Query: Total number of wallets sent out each session? 

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#117]
Audruis, regarding the total number of wallets sent out in each session: If on the closing down screen, 'scanned out' really means the number of wallets sent out (including those scanned in and sent out again, there still seems to be something not right: On Saturday there were 84 wallets shown as scanned in but 81 wallets shown as scanned out. I don't think that can be right. We weren't manually counting but  I guess that at least 20 must have been scanned out (not scanned in). I also doubt that 104 wallets in total were sent out. I'd be gratefull if you can look at the calculation again so we can have a figure for the total muber of wallets sent out to our listeners in a session.  Thanks, Chris

**Comment by audrius-a** [comment]
Were there any duplicate wallets scanned in? The second and third wallets are not counted towards scanned out. If it shows that 84 wallets were scanned out that is the number that should have been sent out, not 104. My simple test shows that it is calculating correctly but there might be some conditions I didn't check. The only thing I can think of is checking the actual database (you would need to send it to me privately). But I would suggest to do an actual count next time and double check the numbers against real values.

**Comment by achrisdale** [comment]
Yes, there were quite a few duplicate wallets scanned in. These of course went back into stock. I didn't bring a copy of the data home on Saturday.  OK. Maybe I need to go in to get a copy before the next session in 2 weeks time so I can check again at home.

**Comment by audrius-a** [comment]
@achrisdale, do you still need this looked into or can I close this issue?

**Comment by achrisdale** [comment]
I think that this can be closed. If we find later after checking manually that the number of wallets sent out does not equal 'Scanned out' we can open a new issue.  As mention in #125 as I think we agree that 'Weekly wallets as of today' means 'Current number of active listeners' then that label text can be changed.
