### ISSUE TITLE
Query: Help Document

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#118]
Audrius, I have imported my 'TNBaseHelp' .rtf document into a HelpNDoc file. It is just a straight import at present and will need some further work.  I have been trying to follow your guidance to upload it to GitHub  TNBase/Docs, or maybe merge it with the existing  'Help Documentation.hnd' file.  Git Hub isn't letting me do either of those things. I am logged in to GitHub as far as I can see. I tried to attach my 'TNBaseHelp.hnd' file here but GitHub won't let me do that either so I'll e-mail it to you. Not sure what I'm doing wrong.
Chris

**Comment by audrius-a** [comment]
Hi Chris, I'm afraid the GitHub would not be able to merge your `.hnd` file with the existing one. It would simply override the existing one completely. Therefore it is crucial to follow these steps:

1. Clone the TNBase repository, or pull the latest changes;
2. Create a new branch based on the latest `master` branch;
3. Open the existing `Docs/Help Documentation.hnd` file in the HelpNDoc application;
4. Amend the file as required and save it;
5. Generate `chm` documentation using HelpNDoc;
6. Copy the newly generated chm file to `src/TNBase/Resource/TNBase.chm` overriding the existing file;
7. Commit the changes to your branch (not `master`);
8. Create a Pull Request in GitHub;

I can help you with any or all of the above. Then, once the Pull Request is created, I will review it and merge it to the `master` branch.

By the way, it would be great if your imported documentation would be broken down into appropriate table of contents sections. At the moment it's just a single page with everything in it. Again, I probably could help you with that.

**Comment by achrisdale** [comment]
OK. Thanks Audrius. I have look at that tomorrow. I'll let you know if I need help.
They seem to make what should be a simple procedure, quite difficult!
Yes, I noticed that the .hnd file needs to broken up into sections, which I expect can then be accessed from a menu. I thought that could come later as long as I can edit the help document once it has been added into TNBase.  As it is at present, it might be of useful to those in Birminham when they start to use TNBase.

**Comment by achrisdale** [comment]
Hi, I'm not sure what I need to do: I assume 'Clone' means make a copy of the whole repository. If so, not sure how to do that. Don't know what 'Pull' means although I can see the 'Pull requests' menu item and then 'new Pull requests' then 'Create pull request'. Not sure what to do with that.

**Comment by audrius-a** [comment]
GitHub is rather complicated for documentation changes that you want to do. Unfortunately, I do not have a better option as GitHub is essential for application development and maintaining the history of it. I do not expect you to learn all this and that is why I suggested that I could help with updating the documentation.

On the other hand, it might be useful to understand the terminology of GitHub and the basic use of it. I found this video that seems to explain it simply and clearly: https://www.youtube.com/watch?v=8Dd7KRpKeaE
It doesn't mention cloning but that is what you would do with the existing repository (as opposed to creating a new repository as in the video) to copy it to your local machine. It's just a menu option in GitHub Desktop under File -> Clone repository...
"Pull" is the opposite action of "Push" that is described in the video, which basically means - get the latest version of the code to your local machine.

There are other videos and materials for how to use GitHub and GitHub Desktop so just search around in Youtube or Google.
We could also setup a remote session where I can show you how it works.

One thing I would ask you is to never commit or push changes directly to the "master" branch as that one should always be a working "clean" version of the code. Just create a new branch of the master as shown in the video and push your changes. Let me know the branch name when ready and I can sort out the Pull Request for you.

**Comment by achrisdale** [comment]
Thanks Audrius.
I'll have a look at the video before asking for further help.
OK, warning noted!

Also thanks for your other message. I'm sure Tom will be pleased to hear 
from you even if you just explain that you have been too busy.

Regards,

Chris

In message ***@***.***>

**Comment by achrisdale** [comment]
Thanks for the link to the Git Hub video. Sorry for the delay, I have been dealing with issues on this Windows PC with the help of a friend. Anyway, I have now done: Pull request -> New pull request -> Create pull request (with allow edits... ticked) -> then I selected the latest commit (4 Nov 2023 (#115)). I get a page of source code with a warning "This commit does not belong to any branch...". I was hoping for an option to save the repository onto my PC but can't see that option. Not sure what to next.

Once I have the clone copy of the repository I can look at following the rest of your list of instructions.

**Comment by achrisdale** [comment]
Just Looked at: Code -> Create a Branch.  I think I have created a branch called: 'HelpDocChris'  but can't see how to get the copy of the repository to export to my local drive. Still not sure if I am on the right track.

**Comment by audrius-a** [comment]
Chris, you can always download the latest version of the document, update and email to me directly. I then can add it to the next release.
![image](https://github.com/achrisdale/TNBase/assets/7377062/b15bbd0d-e342-4044-b803-7de8b02ebeb9)

**Comment by achrisdale** [comment]
Thanks Audrius. I look at doing that tomorrow.

**Comment by achrisdale** [comment]
OK. I imported my Help Document into HelpNDoc again and have tried to generate the .chm document but I get this message: 'The required Microsoft HTML HelpWorkshop CHM compiler hasn't been found on this system. Download and install it or set its path in the options dialog. Download Microsoft's HTML Help Workshop'.
I don't want to download any other app yet because a friend who is helping with other problems on this PC doesn't want me to install anything else until any other Microsoft updates due on Wednesday have been installed and I have made another System Image. (He didn't really want me to install 'HelpNDoc' again after the C: drive had been cleared and Windows10 re-installed).

I'm not sure why there is a reference to 'HTML' because my imported file was an RTF. 

Anyway, the help document I have is the same as that which I e-mailed to you on 28/01/2024. 
If it's easier for you I can wait until I can install Microsoft HTML HelpWorkshop CHM compiler so I can generate the .chm help file.

**Comment by audrius-a** [comment]
I'll take a look at the one you've sent me. It needs to be merged with the existing documentation on listeners import.

**Comment by achrisdale** [comment]
OK Thanks Audrius. If you are too busy we can wait a few more days until I can download the HelpWorkshop CHM compiler.
Incidentally I haven't yet been able to find the GitHub page that you sent me a screen snip of 3 days ago. I'll have another look soon.

**Comment by achrisdale** [comment]
Have now found  the GitHub page that you sent me a screen snip of with the download Icon.

**Comment by achrisdale** [comment]
I have tried to create a .chm file from my .rtf help document. I tried to do as you ask in 5 and 6 of your instructions but not sure that I have been successful. When I imported the .rtf into HelpNDoc the text didn't appear probably because I don't understand what to do so I haven't done anything with my subject headings.
Also not sure if I was successful in importing the .chm file into GitHub. There seem to be two branches from the master: 'HelpDocChris' and 'achrisdale-patch-1' so I tried to import it into both but I can't see it in either. 
I was going to attach it here but GitHub let me attach a .chm file so I'll e-mail it.

**Comment by audrius-a** [comment]
Chris, not sure if you have noticed, but I've closed this issue as completed. I've copied over content of the .rtf file into HelpNDoc document and generated .chm file. You can find it in the master branch under `src/TNBase/Resource/TNBase.chm`.
I didn't create a new release just for that. But I could do it if you like.

**Comment by achrisdale** [comment]
Thanks. However I have found src/TNBase/Resource/TNBase.chm but the same as when I tried to edit it myself, although I opened it and can see that there are some headings in Contents, I can't see any text at all. Do I need some special app to view .chm files? HelpNDoc doesn't seem to be able to view it.

**Comment by achrisdale** [comment]
Thanks Audrius.
I have replied in GibHub Issues #118.

When you do have more time to look at the issues, #114 just to change a 
few words in the text on the Close Down window would be quick and easy.

#111 to add to the printing menu, printing page(s) of return address 
labels would be useful as Tom mentioned but I appreciate that you need to 
work on your new kitchen first.

Chris

**Comment by audrius-a** [comment]
Will be available in the release v1.8.0
