### ISSUE TITLE
New TNBase Release?

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#120]
Hi Audrius, just wondering if you might have time soon to make a TNBase release with the purging of the deleted listeners (Issue #109) included.  I think you did a pre-release with that. I see that we now have over 100 deleted listeners' details waiting to be purged. 

Hopefully the next release would also have the Help document I wrote. (Incidentally I'm still not sure how I will be able to update it when needed).

**Comment by audrius-a** [comment]
Done
