### ISSUE TITLE
V1.8.0 Query.

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#122]
Audrius, NOT urgent: V1.8.0 was installed on my home PC with no problems noted (apart from the string of unwanted characters after the version number on the home page). V1.8.0 installed on the computer at the studio today. All well except that the new form for viewing and updating the list of already deleted listeners could not be viewed because the window was blank apart from the 'Finished' button.  This Windows 10 computer does not get Windows updates because there is no internet connection. Suspect that the missing content in the Deleted Listeners window may be due to a missing Windows 10 update? Would you agree or may there be another reason?

**Comment by audrius-a** [comment]
Fixed in v1.8.1. Please install .Net 8.0 runtime.
