### ISSUE TITLE
Query: Differences between Statistics and History figures 

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#125]
Preparing the Listener number statistics for our AGM, there seems to be a discrepancy between 'Weekly listeners as of today' in the 'Statistics' and the number of wallets 'Scanned out' for the current week in 'History'. (See also #117) What are the calculations for these two figures?  There have been similar questions in the past and I'm not sure if this was resolved.

**Comment by audrius-a** [comment]
The 'Weekly listeners as of today' is the total number of currently Active and Paused listeners. Emphasis on "currently".
The 'Scanned out' is the historical value of wallets sent out that period.

These values should not really match up. I would need to dig deeper to assess if the Scanned Out value is correct. It probably would be easier to keep a paper trail for a bit on how many wallets are being sent out each week to confirm there is no issue with the calculation.

**Comment by achrisdale** [comment]
OK Audrius. I think that the 'Scanned out' figure on an particular Saturday morning is probably correct but we can check manually.  So I would expect that the 'Weekly listeners as of today' would be equal to the 'Scanned out' number plus the number of 'Stopped wallets' plus the number of wallets not sent out because active listeners (if any) had not returned any of their 3 wallets. In other words, because the wallet stock for those listeners was '0'.  Would you agree with that?

**Comment by audrius-a** [comment]
I think your reasoning is correct. Please let me know if that doesn't add up and I'll look into it further. In such case, I probably will need the most recent database.

**Comment by achrisdale** [comment]
OK Thanks. It might take a while to check. 'Weekly listeners as of today' could be re-labelled as 'Current number of active listeners'
