### ISSUE TITLE
Verify the 'Net change of listeners for the year' calculation

### ISSUE THREAD

**Issue by audrius-a** [achrisdale/TNBase#17]
F7: Stats: 'Net change of listeners for the year' doesn't always add up correctly: For example:
'Weekly listeners at the start of this year: 199
Weekly listeners as of today: 190
'Net change of listeners for the year': -4   Should be -9

**Comment by achrisdale** [comment]
This issue seems to be related to the calculations for 'Average number of listeners for the year' and 'Average number of wallets dispatched each week'. Please advise how these three calculations are made as the results don't seem to be correct.
