### ISSUE TITLE
Remove listener contact details from lists that don't require it

### ISSUE THREAD

**Issue by audrius-a** [achrisdale/TNBase#21]
C8: Printing Menu: All the various lists of listeners except the 'Unsent wallet list' which has already been changed: Remove all contact details so that the lists only show wallet numbers and names. The only print out that continues to contain the full details of the listener is to be the 'Print Collector for Listener'. *

**Comment by achrisdale** [comment]
Remove: 'Recently Deleted Listeners' list
Remove: Inactive Listeners This Week' list
Change title of 'Unreturned Memory Stick Players' list to :'memory Stick Players Outstanding'.
Change the details in 'Print Alphabetic (Surname)' list: Delete: DOB and all 'phone numbers, addresses and Joined date.
