### ISSUE TITLE
Add 'Help' to Main Menu. 

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#40]
(C26) Add 'Help' to main menu. This will open TNBase instructions (to be provided).

**Comment by audrius-a** [comment]
Chris, I've introduced Help option with the Listener Import feature. However, there is not much in it at the moment. I used HelpNDoc software which is very easy to use, just like writing a Word document. As it doesn't require development skills, perhaps someone else could take on the task to provide Help content. All is needed is to download software at https://www.helpndoc.com/download/ and edit the file `[TNBase](https://github.com/achrisdale/TNBase)/[Docs](https://github.com/achrisdale/TNBase/tree/master/Docs)/Help Documentation.hnd` in this repository. I could hep setting it all up.

**Comment by achrisdale** [comment]
OK Audrius.
I think that was an early version of the TNBase description in GitHub. I 
have a later rtf version which needs a further update. I wouldn't like to 
have to rewrite it all again. I guess that letting the user search for 
help on particular things would need a lot more work.

Chris

In message ***@***.***>

**Comment by audrius-a** [comment]
It would not be much work to copy rtf content to the HelpNDoc. Maybe just some tidying up of titles and such. I can do that for you.
The search and navigation are available out of the box and with some development we could even make F1 button to take the user to a specific page in the documentation.

**Comment by achrisdale** [comment]
OK. That's good.
I will need to update my document first. Of course some of the issues we 
are dealing with now will affect the help document.

In message ***@***.***>

**Comment by audrius-a** [comment]
This has been done as part of #118
