### ISSUE TITLE
Adjustments to Address Label Printing

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#51]
1. If possible, please reduce the height of the barcode to allow for an extra line of the address:
The existing address boxes on the 'Add' and 'Edit' listener' forms could just be re-labelled 'Address 1', 'Address 2', 'Address 3', 'Address 4' and 'Post Code'. The 4th address box is presently labelled 'County' but isn't used on the printed labels. Where necessary we can still enter two parts of an address on the same line separated with a comma, where there is room.
2. Increase the vertical spacing between the start of printing of the addresses by 1.5mm so that they fit better on the label stationery. If 1.5mm not possible increase the vertical spacing by 2mm.

**Comment by achrisdale** [comment]
3. Please remove the second full stop that appears on the address labels after the Title of the listener. eg: Mr.. etc. also please remove the comma, that appears before the post code.

**Comment by audrius-a** [comment]
At the moment the Town is printed on the same line as Postcode. If I change County to be Line 4 should I put it below that line? I might not be intuitive to the user when adding the address to understand how it will be printed.

**Comment by audrius-a** [comment]
On the other hand, perhaps separating postcode on another line will do the trick. Would this do? 
![image](https://user-images.githubusercontent.com/7377062/159379907-2777257b-7e91-4c85-9c6f-f3a7f75686d3.png)

I have not tested it, but I'm pretty sure the barcode scanner will pick it up.

Also, I don't really like how the wallet number sits there touching the barcode. Unfortunately, I don't have any labels to test so I'm not sure how much room do I have on the right hand side to adjust it.

**Comment by achrisdale** [comment]
Thanks Audrius.
The example you sent looks good to me. Yes, I think the post code does 
belong on a separate line. I guess that you have used a smaller font.
Regarding the bar code and the wallet number: attached is the scan of a 
page of labels that I sent you previously but I have marked in the 
vertical edges of the labels so you can see if the wallet number can be 
moved away from the bar code. Also if the long name you used would be a 
problem. The labels are 63.5mm x 46.6mm (Avery L7161).

I'll ask Linda if she is happy with the layout, but she may not reply 
until later.

Regards,

Chris

In message ***@***.***>

**Comment by achrisdale** [comment]
Hi Audrius,
Linda said yesterday: "If I were doing label printing in Word, I
would just tell it which label type & number I was using & it would
automatically make the text fit. Is the TN system different?"

I don't use MS Word myself but I guess there is a good reason why TNBase 
has it's own method for the layout of labels. Maybe MS word couldn't cope 
with barcodes? We haven't got MS Office on the TN computer anyway although 
we do have the free Open Office.

Incidentally, I have sent Linda copy of your proposed label layout and 
explained that we are looking to see if there is room for a space between 
the bar code and the wallet number.

Regards,

Chris




Thanks Audrius.
The example you sent looks good to me. Yes, I think the post code does 
belong on a separate line. I guess that you have used a smaller font.
Regarding the bar code and the wallet number: attached is the scan of a 
page of labels that I sent you previously but I have marked in the 
vertical edges of the labels so you can see if the wallet number can be 
moved away from the bar code. Also if the long name you used would be a 
problem. The labels are 63.5mm x 46.6mm (Avery L7161).

I'll ask Linda if she is happy with the layout, but she may not reply 
until later.

Regards,

Chris

In message ***@***.***>
