### ISSUE TITLE
Fix TNBase Closing Down Screen

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#57]
The TNBase closing down screen presently just shows '?' in place of the stats. The form doesn't automatically shut down so has to be closed by clicking on the 'X' in the top right corner.

**Comment by audrius-a** [comment]
Fixed for release v1.7.5

**Comment by achrisdale** [comment]
Thanks for the two automated e-mail Audrius.
I'll download V1.7.5 soon.

Chris

In message ***@***.***>

**Comment by audrius-a** [comment]
Chris, the release is not ready yet as I'm hoping to bundle in some other issues. I will let you know when it's available.

**Comment by achrisdale** [comment]
OK Audrius. I'll wait.

Chris

In message ***@***.***>
