### ISSUE TITLE
Changes to 'Add New Listener'

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#68]
Remove the drop-down box for the 'Title' of new listeners in the pop-up form so that Title can be entered from the keyboard.
Change the order of the boxes in the pop-up form for the title and name so that the forename is before the surname, the same as in the main Add New Listener and Edit forms.
Increase the lengths of the boxes for names and addresses in the Pop-up, and main Add New Listener forms so that they are the same as in the Edit form. (Entering in these boxer already scrolls along, which is good).

**Comment by audrius-a** [comment]
Just out of curiosity, why do we need the New Listener popup before the full form? Would it not be better to open the full form straight away bypassing additional popup?

**Comment by audrius-a** [comment]
The Edit Listener Form field has smaller font so more text can fit in. Should I match the font size in Add Listener form or should I keep the larger font and make fields longer to match number of characters visible?
