### ISSUE TITLE
New Listeners who only listen on-line and don't require news or magazine wallets 

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#77]
Add a tick box for adding new listeners who only listen on-line and don't require news or magazine wallets. They will still have a listener (wallet) number. So news and magazine wallet stocks will be set to zero. Make it possible to untick the tick box if the listener subsequently asks for wallets to be sent. Birthday dates recorded as usual. The form should permit entries with or without addresses or 'phone numbers for on-line only listeners.

Add new report: On-Line only Listeners' with the same heading on the report, and sub-title 'No memory sticks to be sent to these listeners'. Names and listener number* only in the report. *Although these listeners won't have wallets or memory stick players, we can give them a listener number which will use the same numbering system as the wallets.

**Comment by audrius-a** [comment]
Chris, I think it would make sense to play the sound "this wallet is online only" when online-only wallet is attempted to scan in. Of course, this would not normally happen but it could be that some existing listeners will become online-only while wallets are still in transit. Could you get an audio recorded for that?

**Comment by achrisdale** [comment]
A good point Audrius. I'll see what Linda thinks. As this may not happen very often would it be less work for you to just have an on-screen warning which says something like "This listener has changed to on-line only. Remove any remaining wallets from stock" ?

**Comment by achrisdale** [comment]
I was going to add that as well as the on-screen warning we might play the 'NotInUse' audio. 
The above comment box seemed to post before I had finished.

**Comment by audrius-a** [comment]
Sounds good. Another question: what should I do with reports and stats? I believe some of them should include online-only while others should only show post wallets. Am I right? Would you be able to compile a list of changes for me?

**Comment by achrisdale** [comment]
OK. I'll look at all the TNBase reports to see what if any changes are needed for on-line only listeners.

**Comment by achrisdale** [comment]
For the reports in the Printing menu, we can include on-line only listeners in the 'Upcomming birthdays'; 'Recently added listeners'; and 'Recently deleted listeners' reports. Ideally adding an asterisk* after the on-line listeners' names and a note underneath the title: ' * on-line only listeners'.  For the Stats: I think they can be included in the all the items which include the word 'listeners' but not for the items which include the word 'wallets' with a note under the title 'Includes on-line only listeners'. If this makes the coding changes very complicated let me know and we can reconsider.

**Comment by achrisdale** [comment]
Correction: the 'Recently deleted listeners' report is to be removed anyway (#80 Changes to Print menu) so no point in adding on-line listeners.
Yes, please add 'Print Alphabetic (Surname) List' to the reports which should include on-line only listeners. 
Yes, if a listener changes to be an on-line only listener and they have a memory stick player then they can be included in the report for 'Unreturned Memory Stick Players'.

**Comment by achrisdale** [comment]
OK Audrius.
You are right. I have added further comments for #77.
Let me know if you see anything else I have overlooked.

Regards,

Chris
