### ISSUE TITLE
Changes to Print Menu

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#80]
Listeners inactive for 30 days: Change subtitle on the report to: Wallets not sent/received for over 30 days. Delete 'Current Date' but keep 'Printed on' date at the bottom of each page. Delete '(No stop in place)' with each entry.

Recently Deleted Listeners: Remove completely. Issue #46 now closed)

Stopped Listener List: Remove completely (Issue #36 now closed)

Inactive Listeners This Week: Rename as: 'Paused Wallet List'; Change the report heading to: 'Paused Wallet List'; Remove listeners' addresses from the report but keep 'Phone numbers. (Issue #46 now closed)

Wallets Not Sent Out: Rename as 'Unsent Wallets This Week'. In the report, remove 'Paused' listeners so that the report only includes 'Active' listeners.

Print Alphabetic (Surname) List: In the report, remove all the listeners' details except the name and wallet number. Keep: Total mumber of listeners and the Printed date.

**Comment by audrius-a** [comment]
I moved Online listener report to #77 as it's closely related.

**Comment by achrisdale** [comment]
OK. Audrius.
Should have mentioned that the form should permit entries with or without 
addresses or 'phone numbers for on-line only listeners.

Thanks,

Chris

In message ***@***.***>
