### ISSUE TITLE
Remove The Warning That Scanning In has already been done when scanning in is selected for News wallets if only Magazine Wallets have been scanned in.

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#82]
If only magazine wallets have already been scanned in that week, remove any warning that wallets have already been scanned in when News Scan In is selected.  If only news wallets have been scanned in that week, remove any warning that wallets have already been scanned in when Magazine Scan In is selected.

**Comment by audrius-a** [comment]
Chris, this needs some clarification. As far as I can see, the Magazine scanning has no warning at all and its scanning doesn't cause any warning for News scanning either. I can't see what needs to be removed. Do you want me to add a warning when Magazines have been scanned already?

**Comment by achrisdale** [comment]
Hi Audrius,
I just checked v1.7.5. As you say there is no warning that scanning has 
already been done for News or Magazine wallets that I have found so far. I 
think this was to avoid a mistake if one person had already done the 
scanning in and clicked 'Finish' and then possibly the next day, someone 
else re-scanned in the same wallets. I'm wondering if there used to be 
such an on-screen warning box. I'll ask Linda. Please don't worry about it 
now.

Regards,

Chris


In message ***@***.***>

**Comment by achrisdale** [comment]
OK, yes. I hadn't closed the app before trying a re-scan in.

So this issue is saying that we don't want a warning that News wallets 
have already been scanned in when Magazine wallets are scanned in. So in 
other words News and Magazine wallet scanning can be treated as completely 
separate. I don't think we are asking for a warning about multiple 
magazine wallet scanning.  Is that OK?

Chris

**Comment by audrius-a** [comment]
That's what I'm trying to explain. News and Magazine wallets are treated separately and only news wallets scan in triggers a warning. Unless there is some unexpected behaviour, at the moment scanning in magazines will not result in a warning for News.

**Comment by achrisdale** [comment]
OK Audrius.
That is OK and what we want. Sorry if I hadn't explain it well.
I had understood that there had been a warning about News wallets having 
already been scanned when Magazine wallets were scanned. If that is not 
the case then this issue can be closed.

Chris

**Comment by audrius-a** [comment]
OK, I'll close it for now. Feel free to reopen it if I missed something.
