### ISSUE TITLE
Make printed reports exportable.

### ISSUE THREAD

**Issue by achrisdale** [achrisdale/TNBase#98]
Please make the printed reports exportable as well as printable so that they can be e-mailed as attachments. 
They could be .rtf or similar file type or even text files. Useful for both Solihull and other TNs.
Medium priority. Include 'Print Collector For Listener'.

**Comment by audrius-a** [comment]
Chris, I'm not sure what you mean by 'Print Collector For Listener'. Is that a separate report? If so, it should be a separate issue with more details of what that report should look like and what data should it include.

As for this particular requirement, would printing to PDF be acceptable? This should be already available on Windows. Just select "Microsoft Print to PDF" or similar printer.
![image](https://user-images.githubusercontent.com/7377062/217664276-864fccd2-7094-46c6-934d-9d9748478582.png)

**Comment by achrisdale** [comment]
Hi Audrius,
'Print Collector For Listener' is already one of the items in the 'Print' 
menu and is also offered when a new listeners' details have been added or 
when a listener has been deleted.

Printing to pdf would be OK if that is easiest. I had thought that if it 
was just plain text then comments could be added later if needed, before 
e-mailing. Not sure how easy that would be if a pdf file. However I don't 
want to ask for anything complicated.

Regards,

Chris

In message ***@***.***>

**Comment by audrius-a** [comment]
Printing to a Word document would require a third-party library and significant development to recreate reports. I think that's not worth the effort off chance that someone would want to add comments. Especially since the Print to PDF option is already there. Of course, if you really need this feature above all other work then we can look into it further.

**Comment by achrisdale** [comment]
OK. Are the existing printed reports PDFs? Is displaying and printing PDFs 
built into Windows 10 etc?  I installed Open Office which is free, onto 
our TNBase computer. I think we can manage without being able to add 
comments onto forms such as the request to a volunteer to deliver or 
collect a memory stick player, although it would have been nice to have.

Chris

In message ***@***.***>

**Comment by audrius-a** [comment]
Yes, "Save as PDF" is a built in printer in Windows. Nice to have depends
on priorities, so if this is important just put it higher in the list. But
I don't think WinForms reports are easily translatable to doc format.

**Comment by achrisdale** [comment]
OK. Let's leave that until later.

In message ***@***.***>

**Comment by achrisdale** [comment]
I have found the option to print to PDF on my home PC so agreed that we don't need this issue, so I'll close it.
